### ISSUE TITLE
Cannot find module 'crypto-js/sha256'

### ISSUE THREAD

**Issue by davidlandais** [Kaperskyguru/adonis-cache#10]
Your file engine FileCache require crypto-js/sha256 but you don't specify it in your package.json.
In dependencies, only "crypto" is specified. Also, you should prefer "import" over "require" for consistency.
May be you should use Hash from Adonis/core. Bcrypt is already installed or Aragon. If it can fit to your needs.

**Comment by Kaperskyguru** [comment]
Fixed with this commit #11
