### ISSUE TITLE
Cannot find module 'crypto-js/sha256'

### ISSUE THREAD

**Issue by Roberto99Roberto99** [Kaperskyguru/adonis-cache#13]
**During the installation of the package I received the following warning:**

PS C:\Users\Roberto\Documents\Clientes\Abc\backend> npm i @kaperskyguru/adonis-cache
npm WARN deprecated crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.

**After installing, I ignored the warning and continued and now I'm getting this error message:**

**Cannot find module 'crypto-js/sha256'**
Require stack:
- C:\Users\Roberto\Documents\Clientes\Abc\backend\node_modules\@kaperskyguru\adonis-cache\build\src\Engines\FileCache.js
- C:\Users\Roberto\Documents\Clientes\Abc\backend\node_modules\@kaperskyguru\adonis-cache\build\src\Services\FileCacheService.js
- C:\Users\Roberto\Documents\Clientes\Abc\backend\node_modules\@kaperskyguru\adonis-cache\build\src\CacheLoader.js
- C:\Users\Roberto\Documents\Clientes\Abc\backend\node_modules\@kaperskyguru\adonis-cache\build\providers\CacheProvider.js
- C:\Users\Roberto\Documents\Clientes\Abc\backend\node_modules\@poppinss\utils\build\src\esmRequire.js
- C:\Users\Roberto\Documents\Clientes\Abc\backend\node_modules\@poppinss\utils\build\index.js
- C:\Users\Roberto\Documents\Clientes\Abc\backend\node_modules\@adonisjs\require-ts\build\src\Compiler\index.js
- C:\Users\Roberto\Documents\Clientes\Abc\backend\node_modules\@adonisjs\require-ts\build\index.js
- C:\Users\Roberto\Documents\Clientes\Abc\backend\node_modules\@adonisjs\assembler\build\src\requireHook\index.js
- C:\Users\Roberto\Documents\Clientes\Abc\backend\node_modules\@adonisjs\assembler\build\register.js
- internal/preload

err: {
  "type": "Error",
  "message": "Cannot find module 'crypto-js/sha256'\nRequire stack:\n- C:\\Users\\Roberto\\Documents\\Clientes\\Abc\\backend\\node_modules\\@kaperskyguru\\adonis-cache\\build\\src\\Engines\\FileCache.js\n- C:\\Users\\Roberto\\Documents\\Clientes\\Abc\\backend\\node_modules\\@kaperskyguru\\adonis-cache\\build\\src\\Services\\FileCacheService.js\n- C:\\Users\\Roberto\\Documents\\Clientes\\Abc\\backend\\node_modules\\@kaperskyguru\\adonis-cache\\build\\src\\CacheLoader.js\n- C:\\Users\\Roberto\\Documents\\Clientes\\Abc\\backend\\node_modules\\@kaperskyguru\\adonis-cache\\build\\providers\\CacheProvider.js\n- C:\\Users\\Roberto\\Documents\\Clientes\\Abc\\backend\\node_modules\\@poppinss\\utils\\build\\src\\esmRequire.js\n- C:\\Users\\Roberto\\Documents\\Clientes\\Abc\\backend\\node_modules\\@poppinss\\utils\\build\\index.js\n- C:\\Users\\Roberto\\Documents\\Clientes\\Abc\\backend\\node_modules\\@adonisjs\\require-ts\\build\\src\\Compiler\\index.js\n- C:\\Users\\Roberto\\Documents\\Clientes\\Abc\\backend\\node_modules\\@adonisjs\\require-ts\\build\\index.js\n- C:\\Users\\Roberto\\Documents\\Clientes\\Abc\\backend\\node_modules\\@adonisjs\\assembler\\build\\src\\requireHook\\index.js\n- C:\\Users\\Roberto\\Documents\\Clientes\\Abc\\backend\\node_modules\\@adonisjs\\assembler\\build\\register.js\n- internal/preload",
  "stack":
      Error: Cannot find module 'crypto-js/sha256'
      Require stack:
      - C:\Users\Roberto\Documents\Clientes\Abc\backend\node_modules\@kaperskyguru\adonis-cache\build\src\Engines\FileCache.js
      - C:\Users\Roberto\Documents\Clientes\Abc\backend\node_modules\@kaperskyguru\adonis-cache\build\src\Services\FileCacheService.js
      - C:\Users\Roberto\Documents\Clientes\Abc\backend\node_modules\@kaperskyguru\adonis-cache\build\src\CacheLoader.js
      - C:\Users\Roberto\Documents\Clientes\Abc\backend\node_modules\@kaperskyguru\adonis-cache\build\providers\CacheProvider.js
      - C:\Users\Roberto\Documents\Clientes\Abc\backend\node_modules\@poppinss\utils\build\src\esmRequire.js
      - C:\Users\Roberto\Documents\Clientes\Abc\backend\node_modules\@poppinss\utils\build\index.js
      - C:\Users\Roberto\Documents\Clientes\Abc\backend\node_modules\@adonisjs\require-ts\build\src\Compiler\index.js
      - C:\Users\Roberto\Documents\Clientes\Abc\backend\node_modules\@adonisjs\require-ts\build\index.js
      - C:\Users\Roberto\Documents\Clientes\Abc\backend\node_modules\@adonisjs\assembler\build\src\requireHook\index.js
      - C:\Users\Roberto\Documents\Clientes\Abc\backend\node_modules\@adonisjs\assembler\build\register.js
      - internal/preload
          at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
          at Function.Module._load (internal/modules/cjs/loader.js:746:27)
          at Module.require (internal/modules/cjs/loader.js:974:19)
          at require (internal/modules/cjs/helpers.js:92:18)
          at Object.<anonymous> (C:\Users\Roberto\Documents\Clientes\Abc\backend\node_modules\@kaperskyguru\adonis-cache\build\src\Engines\FileCache.js:4:16)
          at Module._compile (internal/modules/cjs/loader.js:1085:14)
          at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
          at Module.load (internal/modules/cjs/loader.js:950:32)
          at Function.Module._load (internal/modules/cjs/loader.js:790:14)
          at Module.require (internal/modules/cjs/loader.js:974:19)
  "code": "MODULE_NOT_FOUND",
  "requireStack": [
    "C:\\Users\\Roberto\\Documents\\Clientes\\Abc\\backend\\node_modules\\@kaperskyguru\\adonis-cache\\build\\src\\Engines\\FileCache.js",
    "C:\\Users\\Roberto\\Documents\\Clientes\\Abc\\backend\\node_modules\\@kaperskyguru\\adonis-cache\\build\\src\\Services\\FileCacheService.js",
    "C:\\Users\\Roberto\\Documents\\Clientes\\Abc\\backend\\node_modules\\@kaperskyguru\\adonis-cache\\build\\src\\CacheLoader.js",
    "C:\\Users\\Roberto\\Documents\\Clientes\\Abc\\backend\\node_modules\\@kaperskyguru\\adonis-cache\\build\\providers\\CacheProvider.js",
    "C:\\Users\\Roberto\\Documents\\Clientes\\Abc\\backend\\node_modules\\@poppinss\\utils\\build\\src\\esmRequire.js",
    "C:\\Users\\Roberto\\Documents\\Clientes\\Abc\\backend\\node_modules\\@poppinss\\utils\\build\\index.js",
    "C:\\Users\\Roberto\\Documents\\Clientes\\Abc\\backend\\node_modules\\@adonisjs\\require-ts\\build\\src\\Compiler\\index.js",
    "C:\\Users\\Roberto\\Documents\\Clientes\\Abc\\backend\\node_modules\\@adonisjs\\require-ts\\build\\index.js",
    "C:\\Users\\Roberto\\Documents\\Clientes\\Abc\\backend\\node_modules\\@adonisjs\\assembler\\build\\src\\requireHook\\index.js",
    "C:\\Users\\Roberto\\Documents\\Clientes\\Abc\\backend\\node_modules\\@adonisjs\\assembler\\build\\register.js",
    "internal/preload"
  ],
  "status": 500
}

**Comment by Roberto99Roberto99** [comment]
**I'm a beginner, I think I managed to solve it, could you check for me?**

src/Engines/FileCache.ts

**var crypto = require("crypto");**
~~// const sha256 = require('crypto-js/sha256');~~

hashKey(key) {
       **return crypto.createHash("sha256") + '';**
       ~~// return sha256(key) + '';~~
}

**I made these changes and so far it's not giving any errors.**

**Comment by Kaperskyguru** [comment]
Closed by: https://github.com/Kaperskyguru/adonis-cache/commit/b7173dcb4e7b859bbf3b20a861cafba1424805f9
