### ISSUE TITLE
Error loading Redis config

### ISSUE THREAD

**Issue by SkelatorIndy** [Kaperskyguru/adonis-cache#8]
I was following the tutorial here:
[https://www.section.io/engineering-education/how-to-implement-caching-in-adonisjs-5](url)
and when I attempted to test, it gave the error:
`Define config for "[object Object]" connection inside "config/redix" file`

I traced it through to figure out if I could find the issue, and it seems that the adonis-cache package pulls the entire config object from Adonis, so
`
{
    local: {
      host: Env.get('REDIS_HOST'),
      port: Env.get('REDIS_PORT'),
      password: Env.get('REDIS_PASSWORD', ''),
      db: 0,
      keyPrefix: '',
    }
}
`
and passes that into the @adonis/redis package to load the config. This causes the Adonis Redis package to try to load a config with a name of that object, instead of just the name from the object or the already fetched config object.

I'm not sure if I set something up wrong and it's incorrectly trying to use the whole object when I should have set it somewhere to use the name, but if it is an issue then the solution should just be to extract the name from the config and just pass that through.
Just wanted to leave an issue to get some feedback on if I'm doing something wrong or if it's a bug

**Comment by Kaperskyguru** [comment]
I didn't know this is still an issue. I will send in a fix.

**Comment by Kaperskyguru** [comment]
Closed by: https://github.com/Kaperskyguru/adonis-cache/releases/tag/v2.1.1
